---

addons:
  chrome: stable

language: ruby

sudo: false

dist: trusty

bundler_args: --without development

cache: bundler

before_script:
  - bin/install_chromedriver.sh
  - unset _JAVA_OPTIONS

before_install:
  - gem uninstall -v '>= 2' -i $(rvm gemdir)@global -ax bundler || true
  - gem install bundler -v '< 2'

script:
  - bundle exec rake
  - bundle exec rake docs:build

rvm:
  - 2.7
  - 2.5
  - jruby-9.2

gemfile:
  - gemfiles/rails_60.gemfile
  - gemfiles/rails_50.gemfile
  - gemfiles/rails_51.gemfile
  - gemfiles/rails_52.gemfile

env:
  global:
    - JRUBY_OPTS="-J-Xmx1024m --dev --debug"
    - COVERAGE=true

matrix:
  fast_finish: true

  allow_failures:
    - rvm: jruby-9.2
