---

language: ruby

sudo: false

dist: trusty

bundler_args: --without development

cache: bundler

before_script:
  - unset _JAVA_OPTIONS

before_install:
  - PATH=$(npm bin):$PATH # needed to install phantomjs via npm
  - if [ $(phantomjs --version) != '2.1.1' ]; then npm install phantomjs-prebuilt@2.1; fi
  - gem uninstall -v '>= 2' -i $(rvm gemdir)@global -ax bundler || true
  - gem install bundler -v '< 2'

script:
  - bundle exec rake
  - bundle exec rake docs:build

rvm:
  - 2.7
  - 2.5
  - jruby-9.2

gemfile:
  - gemfiles/rails_61.gemfile
  - gemfiles/rails_60.gemfile
  - gemfiles/rails_52.gemfile

env:
  global:
    - JRUBY_OPTS="-J-Xmx1024m --dev --debug"
    - COVERAGE=true

matrix:
  fast_finish: true

  allow_failures:
    - rvm: jruby-9.2
    - gemfile: gemfiles/rails_61.gemfile